name = "Smp 5"
author = "the gang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "090252b16eb13aafa50466d6ec88226f870155c39aef671e6148d589e7fce8e8"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.1"]
