name = "Smp 5"
author = "the gang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3197a7cffa609cc4de8d3283ead4b70b86d2f7eeb7258c37ccb33fc189d1bbc4"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.1"]
