name = "Smp 5"
author = "the gang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c5620335045d8961cfd95b15e768b210ff5f632ff217515e675084b4decbcdc"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.1"]
